name: Mypy
on: [push, pull_request]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/checkout@v3
      - name: Install Mypy
        run: pip install mypy
      - name: Install types
        run: mypy --install-types --non-interactive .
      - name: Run Mypy
        run: mypy .
